/*
 * Copyright (c) 2017, OpenAV Productions,
 * Harry van Haaren <harryhaaren@gmail.com>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
 * IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
 * TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
 * PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 * TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef OPENAV_CTLRA_NI_KONTROL_S2_H
#define OPENAV_CTLRA_NI_KONTROL_S2_H

enum NI_KONTROL_S2_ENCODERS {
	NI_KONTROL_S2_ENCODER_JOG_WHEEL_LEFT = 0,
	NI_KONTROL_S2_ENCODER_JOG_WHEEL_RIGHT = 1,
	NI_KONTROL_S2_ENCODER_DECKA_LEFT_ENCODER = 2,
	NI_KONTROL_S2_ENCODER_DECKA_RIGHT_ENCODER = 3,
	NI_KONTROL_S2_ENCODER_BROWSE_ENCODER = 4,
	NI_KONTROL_S2_ENCODER_DECKB_LEFT_ENCODER = 5,
	NI_KONTROL_S2_ENCODER_DECKB_RIGHT_ENCODER = 6,
};

enum NI_KONTROL_S2_SLIDERS {
	NI_KONTROL_S2_SLIDER_CROSSFADER,
	NI_KONTROL_S2_SLIDER_PITCH_L   ,
	NI_KONTROL_S2_SLIDER_PITCH_R   ,
	NI_KONTROL_S2_SLIDER_CUE_MIX   ,
	NI_KONTROL_S2_SLIDER_REMIX     ,
	NI_KONTROL_S2_SLIDER_MAIN_LEVEL,
	NI_KONTROL_S2_SLIDER_LEVEL     ,
	NI_KONTROL_S2_SLIDER_FADER_L   ,
	NI_KONTROL_S2_SLIDER_FADER_R   ,
	NI_KONTROL_S2_SLIDER_FX_L_DRY  ,
	NI_KONTROL_S2_SLIDER_FX_L_1    ,
	NI_KONTROL_S2_SLIDER_FX_L_2    ,
	NI_KONTROL_S2_SLIDER_FX_L_3    ,
	NI_KONTROL_S2_SLIDER_FX_R_DRY  ,
	NI_KONTROL_S2_SLIDER_FX_R_1    ,
	NI_KONTROL_S2_SLIDER_FX_R_2    ,
	NI_KONTROL_S2_SLIDER_FX_R_3    ,
	NI_KONTROL_S2_SLIDER_EQ_L_HI   ,
	NI_KONTROL_S2_SLIDER_EQ_L_MID  ,
	NI_KONTROL_S2_SLIDER_EQ_L_LOW  ,
	NI_KONTROL_S2_SLIDER_EQ_R_HI   ,
	NI_KONTROL_S2_SLIDER_EQ_R_MID  ,
	NI_KONTROL_S2_SLIDER_EQ_R_LOW  ,
};

enum NI_KONTROL_S2_BUTTONS {
	NI_KONTROL_S2_BTN_DECKB_PLAY = 0,
	NI_KONTROL_S2_BTN_DECKB_CUE,
	NI_KONTROL_S2_BTN_DECKB_SYNC,
	NI_KONTROL_S2_BTN_DECKB_SHIFT,
	NI_KONTROL_S2_BTN_DECKB_CUE_4,
	NI_KONTROL_S2_BTN_DECKB_CUE_3,
	NI_KONTROL_S2_BTN_DECKB_CUE_2,
	NI_KONTROL_S2_BTN_DECKB_CUE_1,
	NI_KONTROL_S2_BTN_DECKA_JOG_PRESS,
	NI_KONTROL_S2_BTN_DECKB_JOG_PRESS,
	/* back panel switch, off = booth, on = main */
	NI_KONTROL_S2_BTN_MAIN_BOOTH_SWITCH,
	NI_KONTROL_S2_BTN_MIC_ENGAGE,
	NI_KONTROL_S2_BTN_DECKB_MIXER_CUE,
	NI_KONTROL_S2_BTN_DECKB_FLUX,
	NI_KONTROL_S2_BTN_DECKB_LOOP_IN,
	NI_KONTROL_S2_BTN_DECKB_LOOP_OUT,
	NI_KONTROL_S2_BTN_DECKA_PLAY,
	NI_KONTROL_S2_BTN_DECKA_CUE,
	NI_KONTROL_S2_BTN_DECKA_SYNC,
	NI_KONTROL_S2_BTN_DECKA_SHIFT,
	NI_KONTROL_S2_BTN_DECKA_CUE_4,
	NI_KONTROL_S2_BTN_DECKA_CUE_3,
	NI_KONTROL_S2_BTN_DECKA_CUE_2,
	NI_KONTROL_S2_BTN_DECKA_CUE_1,
	NI_KONTROL_S2_BTN_REMIX_ON_B,
	NI_KONTROL_S2_BTN_REMIX_ON_A,
	NI_KONTROL_S2_BTN_BROWSE_LOAD_B,
	NI_KONTROL_S2_BTN_BROWSE_LOAD_A,
	NI_KONTROL_S2_BTN_DECKA_MIXER_CUE,
	NI_KONTROL_S2_BTN_DECKA_FLUX,
	NI_KONTROL_S2_BTN_DECKA_LOOP_IN,
	NI_KONTROL_S2_BTN_DECKA_LOOP_OUT,

	NI_KONTROL_S2_BTN_FX2_DRY_WET,
	NI_KONTROL_S2_BTN_FX2_3,
	NI_KONTROL_S2_BTN_FX2_2,
	NI_KONTROL_S2_BTN_FX2_1,
	NI_KONTROL_S2_BTN_DECKA_GAIN_PRESS,
	NI_KONTROL_S2_BTN_DECKB_GAIN_PRESS,

	NI_KONTROL_S2_BTN_MIXER_B_FX2,
	NI_KONTROL_S2_BTN_MIXER_B_FX1,
	NI_KONTROL_S2_BTN_MIXER_A_FX2,
	NI_KONTROL_S2_BTN_MIXER_A_FX1,
	NI_KONTROL_S2_BTN_FX1_DRY_WET,
	NI_KONTROL_S2_BTN_FX1_3,
	NI_KONTROL_S2_BTN_FX1_2,
	NI_KONTROL_S2_BTN_FX1_1,

	NI_KONTROL_S2_BTN_DECKA_LEFT_ENCODER_PRESS,
	NI_KONTROL_S2_BTN_DECKA_RIGHT_ENCODER_PRESS,
	NI_KONTROL_S2_BTN_BROWSE_ENCODER_PRESS,
	NI_KONTROL_S2_BTN_DECKB_LEFT_ENCODER_PRESS,
	NI_KONTROL_S2_BTN_DECKB_RIGHT_ENCODER_PRESS,
};



#if 0

51 descriptor
4 dA enc left
4 dA enc right
4 Browse enc
4 dB enc left
4 dB enc right
4 dA gain/filter
4 dB gain/filter
4 == waste? ==

#endif

#endif /* OPENAV_CTLRA_NI_KONTROL_S2_H */
