/*
 * Copyright (c) 2016, OpenAV Productions,
 * Harry van Haaren <harryhaaren@gmail.com>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
 * IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
 * TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
 * PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 * TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef OPENAV_CTLRA_NI_KONTROL_X1_MK2_H
#define OPENAV_CTLRA_NI_KONTROL_X1_MK2_H

enum NI_KONTROL_X1_MK2_LEDS {
	/* Left vol LEDs, first 5 blue, last 2 orange */
	NI_KONTROL_X1_MK2_LED_LEFT_FX_1 = 1,
	NI_KONTROL_X1_MK2_LED_LEFT_FX_2,
	NI_KONTROL_X1_MK2_LED_LEFT_FX_3,
	NI_KONTROL_X1_MK2_LED_LEFT_FX_4,
	NI_KONTROL_X1_MK2_LED_RIGHT_FX_1,
	NI_KONTROL_X1_MK2_LED_RIGHT_FX_2,
	NI_KONTROL_X1_MK2_LED_RIGHT_FX_3,
	NI_KONTROL_X1_MK2_LED_RIGHT_FX_4,
	NI_KONTROL_X1_MK2_LED_LEFT_FX_SELECT1,
	NI_KONTROL_X1_MK2_LED_LEFT_FX_SELECT2,
	NI_KONTROL_X1_MK2_LED_LEFT_FX_SELECT_LEFT_ARROW,
	NI_KONTROL_X1_MK2_LED_LEFT_FX_SELECT_RIGHT_ARROW,
	NI_KONTROL_X1_MK2_LED_RIGHT_FX_SELECT_LEFT_ARROW,
	NI_KONTROL_X1_MK2_LED_RIGHT_FX_SELECT_RIGHT_ARROW,
	NI_KONTROL_X1_MK2_LED_RIGHT_FX_SELECT1,
	NI_KONTROL_X1_MK2_LED_RIGHT_FX_SELECT2,
	NI_KONTROL_X1_MK2_LED_LEFT_ARROW,
	NI_KONTROL_X1_MK2_LED_SHIFT,
	NI_KONTROL_X1_MK2_LED_RIGHT_ARROW,
	/* HotCues each support RGB leds - and they are addressed from
	 * left to right (over both left + right decks) - a little messy */
	NI_KONTROL_X1_MK2_LED_LEFT_HOTCUE_1,
	NI_KONTROL_X1_MK2_LED_LEFT_HOTCUE_2 =
		NI_KONTROL_X1_MK2_LED_LEFT_HOTCUE_1 + 3,
	NI_KONTROL_X1_MK2_LED_RIGHT_HOTCUE_1 =
		NI_KONTROL_X1_MK2_LED_LEFT_HOTCUE_2 + 3,
	NI_KONTROL_X1_MK2_LED_RIGHT_HOTCUE_2 =
		NI_KONTROL_X1_MK2_LED_RIGHT_HOTCUE_1 + 3,
	NI_KONTROL_X1_MK2_LED_LEFT_HOTCUE_3 =
		NI_KONTROL_X1_MK2_LED_RIGHT_HOTCUE_2 + 3,
	NI_KONTROL_X1_MK2_LED_LEFT_HOTCUE_4 =
		NI_KONTROL_X1_MK2_LED_LEFT_HOTCUE_3 + 3,
	NI_KONTROL_X1_MK2_LED_RIGHT_HOTCUE_3 =
		NI_KONTROL_X1_MK2_LED_LEFT_HOTCUE_4 + 3,
	NI_KONTROL_X1_MK2_LED_RIGHT_HOTCUE_4 =
		NI_KONTROL_X1_MK2_LED_RIGHT_HOTCUE_3 + 3,
	NI_KONTROL_X1_MK2_LED_LEFT_FLUX =
		NI_KONTROL_X1_MK2_LED_RIGHT_HOTCUE_4 + 3,
	/* Back to sane (over left + right) addresssing for remaining */
	NI_KONTROL_X1_MK2_LED_LEFT_SYNC,
	NI_KONTROL_X1_MK2_LED_RIGHT_FLUX,
	NI_KONTROL_X1_MK2_LED_RIGHT_SYNC,
	NI_KONTROL_X1_MK2_LED_LEFT_CUE,
	NI_KONTROL_X1_MK2_LED_LEFT_PLAY,
	NI_KONTROL_X1_MK2_LED_RIGHT_CUE,
	NI_KONTROL_X1_MK2_LED_RIGHT_PLAY,
	NI_KONTROL_X1_MK2_LED_COUNT,
};

enum NI_KONTROL_X1_MK2_CONTROLS {
	/* Dials */
	NI_KONTROL_X1_MK2_SLIDER_LEFT_FX_1 = 0,
	NI_KONTROL_X1_MK2_SLIDER_LEFT_FX_2,
	NI_KONTROL_X1_MK2_SLIDER_LEFT_FX_3,
	NI_KONTROL_X1_MK2_SLIDER_LEFT_FX_4,
	NI_KONTROL_X1_MK2_SLIDER_RIGHT_FX_1,
	NI_KONTROL_X1_MK2_SLIDER_RIGHT_FX_2,
	NI_KONTROL_X1_MK2_SLIDER_RIGHT_FX_3,
	NI_KONTROL_X1_MK2_SLIDER_RIGHT_FX_4,
	/* Encoders */
	NI_KONTROL_X1_MK2_BTN_ENCODER_MID_ROTATE,
	NI_KONTROL_X1_MK2_BTN_ENCODER_LEFT_ROTATE,
	NI_KONTROL_X1_MK2_BTN_ENCODER_RIGHT_ROTATE,
	/* Buttons */
	NI_KONTROL_X1_MK2_BTN_LEFT_FX_1,
	NI_KONTROL_X1_MK2_BTN_LEFT_FX_2,
	NI_KONTROL_X1_MK2_BTN_LEFT_FX_3,
	NI_KONTROL_X1_MK2_BTN_LEFT_FX_4,
	NI_KONTROL_X1_MK2_BTN_RIGHT_FX_1,
	NI_KONTROL_X1_MK2_BTN_RIGHT_FX_2,
	NI_KONTROL_X1_MK2_BTN_RIGHT_FX_3,
	NI_KONTROL_X1_MK2_BTN_RIGHT_FX_4,
	NI_KONTROL_X1_MK2_BTN_LEFT_FX_SELECT1,
	NI_KONTROL_X1_MK2_BTN_LEFT_FX_SELECT2,
	NI_KONTROL_X1_MK2_BTN_RIGHT_FX_SELECT1,
	NI_KONTROL_X1_MK2_BTN_RIGHT_FX_SELECT2,
	NI_KONTROL_X1_MK2_BTN_LEFT_ARROW,
	NI_KONTROL_X1_MK2_BTN_SHIFT,
	NI_KONTROL_X1_MK2_BTN_RIGHT_ARROW,
	NI_KONTROL_X1_MK2_BTN_ENCODER_RIGHT_PRESS,
	NI_KONTROL_X1_MK2_BTN_RIGHT_1,
	NI_KONTROL_X1_MK2_BTN_RIGHT_2,
	NI_KONTROL_X1_MK2_BTN_RIGHT_3,
	NI_KONTROL_X1_MK2_BTN_RIGHT_4,
	NI_KONTROL_X1_MK2_BTN_RIGHT_FLUX,
	NI_KONTROL_X1_MK2_BTN_RIGHT_SYNC,
	NI_KONTROL_X1_MK2_BTN_RIGHT_CUE,
	NI_KONTROL_X1_MK2_BTN_RIGHT_PLAY,
	NI_KONTROL_X1_MK2_BTN_LEFT_1,
	NI_KONTROL_X1_MK2_BTN_LEFT_2,
	NI_KONTROL_X1_MK2_BTN_LEFT_3,
	NI_KONTROL_X1_MK2_BTN_LEFT_4,
	NI_KONTROL_X1_MK2_BTN_LEFT_FLUX,
	NI_KONTROL_X1_MK2_BTN_LEFT_SYNC,
	NI_KONTROL_X1_MK2_BTN_LEFT_CUE,
	NI_KONTROL_X1_MK2_BTN_LEFT_PLAY,
	NI_KONTROL_X1_MK2_BTN_ENCODER_RIGHT_TOUCH,
	NI_KONTROL_X1_MK2_BTN_ENCODER_MID_TOUCH,
	NI_KONTROL_X1_MK2_BTN_ENCODER_LEFT_TOUCH,
	NI_KONTROL_X1_MK2_BTN_ENCODER_MID_PRESS,
	NI_KONTROL_X1_MK2_BTN_ENCODER_LEFT_PRESS,
	/* Count of all controls */
	NI_KONTROL_X1_MK2_CONTROLS_COUNT
};

#endif /* OPENAV_CTLRA_NI_KONTROL_X1_MK2_H */

