/*
 * Copyright (c) 2016, OpenAV Productions,
 * Harry van Haaren <harryhaaren@gmail.com>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
 * IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
 * TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
 * PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 * TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef OPENAV_CTLRA_NI_MASCHINE_MIKRO_MK2_H
#define OPENAV_CTLRA_NI_MASCHINE_MIKRO_MK2_H

enum NI_MASCHINE_MIKRO_MK2_LEDS {
	/* Left vol LEDs, first 5 blue, last 2 orange */
	NI_MASCHINE_MIKRO_MK2_LED_F1,
	NI_MASCHINE_MIKRO_MK2_LED_F2,
	NI_MASCHINE_MIKRO_MK2_LED_F3,
	NI_MASCHINE_MIKRO_MK2_LED_CONTROL,
	NI_MASCHINE_MIKRO_MK2_LED_NAV,
	NI_MASCHINE_MIKRO_MK2_LED_NAV_LEFT,
	NI_MASCHINE_MIKRO_MK2_LED_NAV_RIGHT,
	NI_MASCHINE_MIKRO_MK2_LED_MAIN,
	NI_MASCHINE_MIKRO_MK2_LED_GROUP, /* RGB */
	NI_MASCHINE_MIKRO_MK2_LED_BROWSE,
	NI_MASCHINE_MIKRO_MK2_LED_SAMPLING,
	NI_MASCHINE_MIKRO_MK2_LED_NOTE_REPEAT,
	NI_MASCHINE_MIKRO_MK2_LED_RESTART,
	NI_MASCHINE_MIKRO_MK2_LED_LEFT,
	NI_MASCHINE_MIKRO_MK2_LED_RIGHT,
	NI_MASCHINE_MIKRO_MK2_LED_GRID,
	NI_MASCHINE_MIKRO_MK2_LED_PLAY, /* Green Only */
	NI_MASCHINE_MIKRO_MK2_LED_REC,  /* Red Only */
	NI_MASCHINE_MIKRO_MK2_LED_ERASE,
	NI_MASCHINE_MIKRO_MK2_LED_SHIFT,
	NI_MASCHINE_MIKRO_MK2_LED_SCENE,
	NI_MASCHINE_MIKRO_MK2_LED_PATTERN,
	NI_MASCHINE_MIKRO_MK2_LED_PAD_MODE,
	NI_MASCHINE_MIKRO_MK2_LED_VIEW,
	NI_MASCHINE_MIKRO_MK2_LED_DUPLICATE,
	NI_MASCHINE_MIKRO_MK2_LED_SELECT,
	NI_MASCHINE_MIKRO_MK2_LED_SOLO,
	NI_MASCHINE_MIKRO_MK2_LED_MUTE,
	/* Pads: RGB */
	NI_MASCHINE_MIKRO_MK2_LED_PAD_1,
	NI_MASCHINE_MIKRO_MK2_LED_PAD_2,
	NI_MASCHINE_MIKRO_MK2_LED_PAD_3,
	NI_MASCHINE_MIKRO_MK2_LED_PAD_4,
	NI_MASCHINE_MIKRO_MK2_LED_PAD_5,
	NI_MASCHINE_MIKRO_MK2_LED_PAD_6,
	NI_MASCHINE_MIKRO_MK2_LED_PAD_7,
	NI_MASCHINE_MIKRO_MK2_LED_PAD_8,
	NI_MASCHINE_MIKRO_MK2_LED_PAD_9,
	NI_MASCHINE_MIKRO_MK2_LED_PAD_10,
	NI_MASCHINE_MIKRO_MK2_LED_PAD_11,
	NI_MASCHINE_MIKRO_MK2_LED_PAD_12,
	NI_MASCHINE_MIKRO_MK2_LED_PAD_13,
	NI_MASCHINE_MIKRO_MK2_LED_PAD_14,
	NI_MASCHINE_MIKRO_MK2_LED_PAD_15,
	NI_MASCHINE_MIKRO_MK2_LED_PAD_16,
	/* Count */
	NI_MASCHINE_MIKRO_MK2_LED_COUNT,
};

enum NI_MASCHINE_MIKRO_MK2_CONTROLS {
	/* Buttons */
	NI_MASCHINE_MIKRO_MK2_BTN_RESTART,
	NI_MASCHINE_MIKRO_MK2_BTN_LEFT_ARROW,
	NI_MASCHINE_MIKRO_MK2_BTN_RIGHT_ARROW,
	NI_MASCHINE_MIKRO_MK2_BTN_GRID,
	NI_MASCHINE_MIKRO_MK2_BTN_PLAY,
	NI_MASCHINE_MIKRO_MK2_BTN_RECORD,
	NI_MASCHINE_MIKRO_MK2_BTN_ERASE,
	NI_MASCHINE_MIKRO_MK2_BTN_SHIFT,
	NI_MASCHINE_MIKRO_MK2_BTN_GROUP,
	NI_MASCHINE_MIKRO_MK2_BTN_BROWSE,
	NI_MASCHINE_MIKRO_MK2_BTN_SAMPLING,
	NI_MASCHINE_MIKRO_MK2_BTN_NOTE_REPEAT,
	NI_MASCHINE_MIKRO_MK2_BTN_ENCODER_PRESS,
	NI_MASCHINE_MIKRO_MK2_BTN_F1,
	NI_MASCHINE_MIKRO_MK2_BTN_F2,
	NI_MASCHINE_MIKRO_MK2_BTN_F3,
	NI_MASCHINE_MIKRO_MK2_BTN_CONTROL,
	NI_MASCHINE_MIKRO_MK2_BTN_NAV,
	NI_MASCHINE_MIKRO_MK2_BTN_NAV_LEFT,
	NI_MASCHINE_MIKRO_MK2_BTN_NAV_RIGHT,
	NI_MASCHINE_MIKRO_MK2_BTN_MAIN,
	NI_MASCHINE_MIKRO_MK2_BTN_SCENE,
	NI_MASCHINE_MIKRO_MK2_BTN_PATTERN,
	NI_MASCHINE_MIKRO_MK2_BTN_PAD_MODE,
	NI_MASCHINE_MIKRO_MK2_BTN_VIEW,
	NI_MASCHINE_MIKRO_MK2_BTN_DUPLICATE,
	NI_MASCHINE_MIKRO_MK2_BTN_SELECT,
	NI_MASCHINE_MIKRO_MK2_BTN_SOLO,
	NI_MASCHINE_MIKRO_MK2_BTN_MUTE,
	/* Encoders */
	NI_MASCHINE_MIKRO_MK2_BTN_ENCODER_ROTATE,
	/* Count of all controls */
	NI_MASCHINE_MIKRO_MK2_CONTROLS_COUNT
};

#endif /* OPENAV_CTLRA_NI_MASCHINE_MIKRO_MK2_H */

