/*
 * Copyright (c) 2016, OpenAV Productions,
 * Harry van Haaren <harryhaaren@gmail.com>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
 * IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
 * TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
 * PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 * TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef OPENAV_CTLRA_NI_MASCHINE_MIKRO_MK3_H
#define OPENAV_CTLRA_NI_MASCHINE_MIKRO_MK3_H

enum NI_MASCHINE_MIKRO_MK3_BUTTONS_LEDS {
    NI_MASCHINE_MIKRO_MK3_LED_NATIVE_INSTRUMENTS,
    NI_MASCHINE_MIKRO_MK3_LED_STAR,
    NI_MASCHINE_MIKRO_MK3_LED_SEARCH,
    NI_MASCHINE_MIKRO_MK3_LED_VOLUME,
    NI_MASCHINE_MIKRO_MK3_LED_SWING,
    NI_MASCHINE_MIKRO_MK3_LED_TEMPO,
    NI_MASCHINE_MIKRO_MK3_LED_PLUG_IN,
    NI_MASCHINE_MIKRO_MK3_LED_SAMPLING,
    NI_MASCHINE_MIKRO_MK3_LED_LEFT_ARROW,
    NI_MASCHINE_MIKRO_MK3_LED_RIGHT_ARROW,
    NI_MASCHINE_MIKRO_MK3_LED_PITCH,
    NI_MASCHINE_MIKRO_MK3_LED_MOD,
    NI_MASCHINE_MIKRO_MK3_LED_PERFORM,
    NI_MASCHINE_MIKRO_MK3_LED_NOTES,
    NI_MASCHINE_MIKRO_MK3_LED_GROUP,
    NI_MASCHINE_MIKRO_MK3_LED_AUTO,
    NI_MASCHINE_MIKRO_MK3_LED_LOCK,
    NI_MASCHINE_MIKRO_MK3_LED_NOTE_REPEAT,
    NI_MASCHINE_MIKRO_MK3_LED_RESTART,
    NI_MASCHINE_MIKRO_MK3_LED_ERASE,
    NI_MASCHINE_MIKRO_MK3_LED_TAP,
    NI_MASCHINE_MIKRO_MK3_LED_FOLLOW,
    NI_MASCHINE_MIKRO_MK3_LED_PLAY,
    NI_MASCHINE_MIKRO_MK3_LED_RECORD,
    NI_MASCHINE_MIKRO_MK3_LED_STOP,
    NI_MASCHINE_MIKRO_MK3_LED_SHIFT,
    NI_MASCHINE_MIKRO_MK3_LED_FIXED_VEL,
    NI_MASCHINE_MIKRO_MK3_LED_PAD_MODE,
    NI_MASCHINE_MIKRO_MK3_LED_KEYBOARD,
    NI_MASCHINE_MIKRO_MK3_LED_CHORDS,
    NI_MASCHINE_MIKRO_MK3_LED_STEP,
    NI_MASCHINE_MIKRO_MK3_LED_SCENE,
    NI_MASCHINE_MIKRO_MK3_LED_PATTERN,
    NI_MASCHINE_MIKRO_MK3_LED_EVENTS,
    NI_MASCHINE_MIKRO_MK3_LED_VARIATION,
    NI_MASCHINE_MIKRO_MK3_LED_DUPLICATE,
    NI_MASCHINE_MIKRO_MK3_LED_SELECT,
    NI_MASCHINE_MIKRO_MK3_LED_SOLO,
    NI_MASCHINE_MIKRO_MK3_LED_MUTE,
    NI_MASCHINE_MIKRO_MK3_LED_PAD13,
    NI_MASCHINE_MIKRO_MK3_LED_PAD14,
    NI_MASCHINE_MIKRO_MK3_LED_PAD15,
    NI_MASCHINE_MIKRO_MK3_LED_PAD16,
    NI_MASCHINE_MIKRO_MK3_LED_PAD9,
    NI_MASCHINE_MIKRO_MK3_LED_PAD10,
    NI_MASCHINE_MIKRO_MK3_LED_PAD11,
    NI_MASCHINE_MIKRO_MK3_LED_PAD12,
    NI_MASCHINE_MIKRO_MK3_LED_PAD5,
    NI_MASCHINE_MIKRO_MK3_LED_PAD6,
    NI_MASCHINE_MIKRO_MK3_LED_PAD7,
    NI_MASCHINE_MIKRO_MK3_LED_PAD8,
    NI_MASCHINE_MIKRO_MK3_LED_PAD1,
    NI_MASCHINE_MIKRO_MK3_LED_PAD2,
    NI_MASCHINE_MIKRO_MK3_LED_PAD3,
    NI_MASCHINE_MIKRO_MK3_LED_PAD4,
};

enum NI_MASCHINE_MIKRO_MK3_CONTROLS {
	/* Buttons */
    /* 1 */
    NI_MASCHINE_MIKRO_MK3_BTN_NATIVE_INSTRUMENTS,
    NI_MASCHINE_MIKRO_MK3_BTN_STAR,
    NI_MASCHINE_MIKRO_MK3_BTN_SEARCH,
    NI_MASCHINE_MIKRO_MK3_BTN_VOLUME,
    NI_MASCHINE_MIKRO_MK3_BTN_SWING,
    NI_MASCHINE_MIKRO_MK3_BTN_TEMPO,
    NI_MASCHINE_MIKRO_MK3_BTN_PLUG_IN,
    NI_MASCHINE_MIKRO_MK3_BTN_SAMPLING,
    /* 2 */
    NI_MASCHINE_MIKRO_MK3_BTN_LEFT_ARROW,
    NI_MASCHINE_MIKRO_MK3_BTN_RIGHT_ARROW,
    NI_MASCHINE_MIKRO_MK3_BTN_PITCH,
    NI_MASCHINE_MIKRO_MK3_BTN_MOD,
    NI_MASCHINE_MIKRO_MK3_BTN_PERFORM,
    NI_MASCHINE_MIKRO_MK3_BTN_NOTES,
    NI_MASCHINE_MIKRO_MK3_BTN_GROUP,
    NI_MASCHINE_MIKRO_MK3_BTN_AUTO,
    /* 3 */
    NI_MASCHINE_MIKRO_MK3_BTN_LOCK,
    NI_MASCHINE_MIKRO_MK3_BTN_NOTE_REPEAT,
    NI_MASCHINE_MIKRO_MK3_BTN_RESTART,
    NI_MASCHINE_MIKRO_MK3_BTN_ERASE,
    NI_MASCHINE_MIKRO_MK3_BTN_TAP,
    NI_MASCHINE_MIKRO_MK3_BTN_FOLLOW,
    NI_MASCHINE_MIKRO_MK3_BTN_PLAY,
    NI_MASCHINE_MIKRO_MK3_BTN_RECORD,
    /* 4 */
    NI_MASCHINE_MIKRO_MK3_BTN_STOP,
    NI_MASCHINE_MIKRO_MK3_BTN_SHIFT,
    NI_MASCHINE_MIKRO_MK3_BTN_FIXED_VEL,
    NI_MASCHINE_MIKRO_MK3_BTN_PAD_MODE,
    NI_MASCHINE_MIKRO_MK3_BTN_KEYBOARD,
    NI_MASCHINE_MIKRO_MK3_BTN_CHORDS,
    NI_MASCHINE_MIKRO_MK3_BTN_STEP,
    NI_MASCHINE_MIKRO_MK3_BTN_SCENE,
    /* 5 */
    NI_MASCHINE_MIKRO_MK3_BTN_PATTERN,
    NI_MASCHINE_MIKRO_MK3_BTN_EVENTS,
    NI_MASCHINE_MIKRO_MK3_BTN_VARIATION,
    NI_MASCHINE_MIKRO_MK3_BTN_DUPLICATE,
    NI_MASCHINE_MIKRO_MK3_BTN_SELECT,
    NI_MASCHINE_MIKRO_MK3_BTN_SOLO,
    NI_MASCHINE_MIKRO_MK3_BTN_MUTE,
    /* Multiple presses */
	/* Encoders */
	NI_MASCHINE_MIKRO_MK3_BTN_ENCODER_ROTATE,
	/* Count of all controls */
	NI_MASCHINE_MIKRO_MK3_CONTROLS_COUNT
};

#endif /* OPENAV_CTLRA_NI_MASCHINE_MIKRO_MK3_H */

