/*
 * Copyright (c) 2016, OpenAV Productions,
 * Harry van Haaren <harryhaaren@gmail.com>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
 * IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
 * TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
 * PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 * TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef OPENAV_CTLR_NI_KONTROL_X1_MK2_H
#define OPENAV_CTLR_NI_KONTROL_X1_MK2_H

enum NI_KONTROL_X1_MK2_LEDS {
	/* Left vol LEDs, first 5 blue, last 2 orange */
	NI_KONTROL_X1_MK2_LED_LEVEL_L1 = 1,
	NI_KONTROL_X1_MK2_LED_LEVEL_L2 = 2,
	NI_KONTROL_X1_MK2_LED_LEVEL_L3 = 3,
	NI_KONTROL_X1_MK2_LED_LEVEL_L4 = 4,
	NI_KONTROL_X1_MK2_LED_LEVEL_L5 = 5,
	NI_KONTROL_X1_MK2_LED_LEVEL_L6 = 6,
	NI_KONTROL_X1_MK2_LED_LEVEL_L7 = 7,

	/* Right vol LEDs, first 5 blue, last 2 orange */
	NI_KONTROL_X1_MK2_LED_LEVEL_R1 = 8,
	NI_KONTROL_X1_MK2_LED_LEVEL_R2 = 9,
	NI_KONTROL_X1_MK2_LED_LEVEL_R3 = 10,
	NI_KONTROL_X1_MK2_LED_LEVEL_R4 = 11,
	NI_KONTROL_X1_MK2_LED_LEVEL_R5 = 12,
	NI_KONTROL_X1_MK2_LED_LEVEL_R6 = 13,
	NI_KONTROL_X1_MK2_LED_LEVEL_R7 = 14,

	NI_KONTROL_X1_MK2_LED_CUE_A = 15,
	NI_KONTROL_X1_MK2_LED_CUE_B = 16,

	/* FX ON supports Orange and Blue colours */
	NI_KONTROL_X1_MK2_LED_FX_ON_LEFT = 17,	/* orange */
	NI_KONTROL_X1_MK2_LED_UNUSED_1 = 18,	/* blue */

	NI_KONTROL_X1_MK2_LED_MODE = 19,

	/* FX ON supports Orange and Blue colours */
	NI_KONTROL_X1_MK2_LED_FX_ON_RIGHT = 20,	/* orange */
	NI_KONTROL_X1_MK2_LED_UNUSED_2 = 21,	/* blue */

	NI_KONTROL_X1_MK2_LED_COUNT,
};

enum NI_KONTROL_X1_MK2_CONTROLS {
	/* Dials */
	NI_KONTROL_X1_MK2_SLIDER_LEFT_FX_1 = 0,
	NI_KONTROL_X1_MK2_SLIDER_LEFT_FX_2 = 1,
	NI_KONTROL_X1_MK2_SLIDER_LEFT_FX_3 = 2,
	NI_KONTROL_X1_MK2_SLIDER_LEFT_FX_4 = 3,
	NI_KONTROL_X1_MK2_SLIDER_RIGHT_FX_1 = 4,
	NI_KONTROL_X1_MK2_SLIDER_RIGHT_FX_2 = 5,
	NI_KONTROL_X1_MK2_SLIDER_RIGHT_FX_3 = 6,
	NI_KONTROL_X1_MK2_SLIDER_RIGHT_FX_4 = 7,
	/* Encoders */
	NI_KONTROL_X1_MK2_BTN_ENCODER_MID_ROTATE = 14,
	NI_KONTROL_X1_MK2_BTN_ENCODER_LEFT_ROTATE = 15,
	NI_KONTROL_X1_MK2_BTN_ENCODER_RIGHT_ROTATE = 16,
	/* Buttons */
	NI_KONTROL_X1_MK2_BTN_LEFT_FX_1 = 21,
	NI_KONTROL_X1_MK2_BTN_LEFT_FX_2 = 22,
	NI_KONTROL_X1_MK2_BTN_LEFT_FX_3 = 23,
	NI_KONTROL_X1_MK2_BTN_LEFT_FX_4 = 24,
	NI_KONTROL_X1_MK2_BTN_RIGHT_FX_1 = 25,
	NI_KONTROL_X1_MK2_BTN_RIGHT_FX_2 = 26,
	NI_KONTROL_X1_MK2_BTN_RIGHT_FX_3 = 27,
	NI_KONTROL_X1_MK2_BTN_RIGHT_FX_4 = 28,
	NI_KONTROL_X1_MK2_BTN_LEFT_FX_SELECT1 = 29,
	NI_KONTROL_X1_MK2_BTN_LEFT_FX_SELECT2 = 30,
	NI_KONTROL_X1_MK2_BTN_RIGHT_FX_SELECT1 = 31,
	NI_KONTROL_X1_MK2_BTN_RIGHT_FX_SELECT2 = 32,
	NI_KONTROL_X1_MK2_BTN_LEFT_ARROW       = 33,
	NI_KONTROL_X1_MK2_BTN_SHIFT            = 34,
	NI_KONTROL_X1_MK2_BTN_RIGHT_ARROW      = 35,
	NI_KONTROL_X1_MK2_BTN_ENCODER_RIGHT    = 36,
	NI_KONTROL_X1_MK2_BTN_RIGHT_1    = 37,
	NI_KONTROL_X1_MK2_BTN_RIGHT_2    = 38,
	NI_KONTROL_X1_MK2_BTN_RIGHT_3    = 39,
	NI_KONTROL_X1_MK2_BTN_RIGHT_4    = 40,
	NI_KONTROL_X1_MK2_BTN_RIGHT_FLUX = 41,
	NI_KONTROL_X1_MK2_BTN_RIGHT_SYNC = 42,
	NI_KONTROL_X1_MK2_BTN_RIGHT_CUE  = 43,
	NI_KONTROL_X1_MK2_BTN_RIGHT_PLAY = 44,
	NI_KONTROL_X1_MK2_BTN_LEFT_1    = 45,
	NI_KONTROL_X1_MK2_BTN_LEFT_2    = 46,
	NI_KONTROL_X1_MK2_BTN_LEFT_3    = 47,
	NI_KONTROL_X1_MK2_BTN_LEFT_4    = 48,
	NI_KONTROL_X1_MK2_BTN_LEFT_FLUX = 49,
	NI_KONTROL_X1_MK2_BTN_LEFT_SYNC = 50,
	NI_KONTROL_X1_MK2_BTN_LEFT_CUE  = 51,
	NI_KONTROL_X1_MK2_BTN_LEFT_PLAY = 52,
	NI_KONTROL_X1_MK2_BTN_ENCODER_RIGHT_TOUCH = 53,
	NI_KONTROL_X1_MK2_BTN_ENCODER_MID_TOUCH   = 54,
	NI_KONTROL_X1_MK2_BTN_ENCODER_LEFT_TOUCH  = 55,
	NI_KONTROL_X1_MK2_BTN_ENCODER_MID_PRESS   = 56,
	NI_KONTROL_X1_MK2_BTN_ENCODER_LEFT_PRESS  = 56,
	/* Count of all controls */
	NI_KONTROL_X1_MK2_CONTROLS_COUNT
};

#endif /* OPENAV_CTLR_NI_KONTROL_X1_MK2_H */

