/*
 * Copyright (c) 2016, OpenAV Productions,
 * Harry van Haaren <harryhaaren@gmail.com>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
 * IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
 * TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
 * PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 * TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef OPENAV_CTLR_NI_MASCHINE_H
#define OPENAV_CTLR_NI_MASCHINE_H

enum NI_MASCHINE_LEDS {
	NI_MASCHINE_LED_F1 = 1,
	NI_MASCHINE_LED_F2 = 2,
	NI_MASCHINE_LED_F3 = 3,
	NI_MASCHINE_LED_CONTROL = 4,
	NI_MASCHINE_LED_NAV = 5,
	NI_MASCHINE_LED_NAV_LEFT = 6,
	NI_MASCHINE_LED_NAV_RIGHT = 7,
	NI_MASCHINE_LED_MAIN = 8,
	NI_MASCHINE_LED_GROUP = 9, /* multi-colour */
	/* 8 as Green component of multi-colour */
	/* 9 as Blue component of multi-colour */
	NI_MASCHINE_LED_BROWSE = 12,
	NI_MASCHINE_LED_SAMPLING = 13,
	NI_MASCHINE_LED_NOTE_REPEAT = 14,
	NI_MASCHINE_LED_RESTART = 15,
	NI_MASCHINE_LED_LEFT = 16,
	NI_MASCHINE_LED_RIGHT = 17,
	NI_MASCHINE_LED_GRID = 18,
	NI_MASCHINE_LED_PLAY = 19,
	NI_MASCHINE_LED_REC = 20,
	NI_MASCHINE_LED_ERASE = 21,
	NI_MASCHINE_LED_SHIFT = 22,
	NI_MASCHINE_LED_SCENE = 23,
	NI_MASCHINE_LED_PATTERN = 24,
	NI_MASCHINE_LED_PAD_MODE = 25,
	NI_MASCHINE_LED_VIEW = 26,
	NI_MASCHINE_LED_DUPLICATE = 27,
	NI_MASCHINE_LED_SELECT = 28,
	NI_MASCHINE_LED_SOLO = 29,
	NI_MASCHINE_LED_MUTE = 30,
};

enum NI_MASCHINE_BTNS {
	NI_MASCHINE_BTN_RESTART = 0,
	NI_MASCHINE_BTN_LEFT = 1,
	NI_MASCHINE_BTN_RIGHT = 2,
	NI_MASCHINE_BTN_GRID = 3,
	NI_MASCHINE_BTN_PLAY = 4,
	NI_MASCHINE_BTN_REC = 5,
	NI_MASCHINE_BTN_ERASE = 6,
	NI_MASCHINE_BTN_SHIFT = 7,
	NI_MASCHINE_BTN_GROUP = 8,
	NI_MASCHINE_BTN_BROWSE = 9,
	NI_MASCHINE_BTN_SAMPLING = 10,
	NI_MASCHINE_BTN_NOTE_REPEAT = 11,
	NI_MASCHINE_BTN_ENCODER_PRESS = 12,
	NI_MASCHINE_BTN_F1 = 13,
	NI_MASCHINE_BTN_F2 = 14,
	NI_MASCHINE_BTN_F3 = 15,
	NI_MASCHINE_BTN_CONTROL = 16,
	NI_MASCHINE_BTN_NAV = 17,
	NI_MASCHINE_BTN_NAV_LEFT = 18,
	NI_MASCHINE_BTN_NAV_RIGHT = 19,
	NI_MASCHINE_BTN_MAIN = 20,
	NI_MASCHINE_BTN_SCENE = 21,
	NI_MASCHINE_BTN_PATTERN = 22,
	NI_MASCHINE_BTN_PAD_MODE = 23,
	NI_MASCHINE_BTN_VIEW = 24,
	NI_MASCHINE_BTN_DUPLICATE = 25,
	NI_MASCHINE_BTN_SELECT = 26,
	NI_MASCHINE_BTN_SOLO = 27,
	NI_MASCHINE_BTN_MUTE = 28,
};

void ni_maschine_screen_blit(struct ctlr_dev_t *dev, uint8_t *bits);

#endif /* OPENAV_CTLR_NI_MASCHINE_H */

